<a href="https://colab.research.google.com/github/dharineeshramtp2000/Gradient-Boosting-Vehicle-Prediction-Silhouette-Measurements-/blob/master/Vehicle_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset. Here we use the dataset from [ML Data](https://www.mldata.io/datasets/).
![](https://www.thestreet.com/.image/ar_3:2%2Cc_limit%2Ccs_srgb%2Cq_auto:good%2Cw_600/MTY4NjUxNDMwMjY4NjQyOTUx/14-gmc-sierra.png)
---

Here we are going to predict the vehicle type based on silhouette measurements

The types of Vehicles are 


1.   Opel
2.   saab
3.   Bus
4.   Van









In [14]:
Dataset = pd.read_csv("vehicle_silhouette_weka_dataset.csv")
X = Dataset.iloc[:,:-1].values
y = Dataset.iloc[:,-1].values
Dataset.describe()

compactness  circularity  ...  kurtosis_major_axis  hollows_ratio
count   846.000000   846.000000  ...           846.000000     846.000000
mean     93.678487    44.861702  ...           188.932624     195.632388
std       8.234474     6.169866  ...             6.163949       7.438797
min      73.000000    33.000000  ...           176.000000     181.000000
25%      87.000000    40.000000  ...           184.000000     190.250000
50%      93.000000    44.000000  ...           188.000000     197.000000
75%     100.000000    49.000000  ...           193.000000     201.000000
max     119.000000    59.000000  ...           206.000000     211.000000

[8 rows x 18 columns]

Lets Feature Scale the independent variables

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

Splitting the dataset into training and testing and performing a good shuffle of data

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.3, random_state =42, shuffle = True)

Now lets define our Gradient Boost Classifier.
We know how trees work. We use these attributes in order to make the splits and finally make the prediction using the leaf values of the tree.
Instead of using normal trees, lets define it using boosting algorithm(**here Gradient Boost**)

![](https://www.frontiersin.org/files/Articles/284242/fnagi-09-00329-HTML/image_t/fnagi-09-00329-g001.gif)

Feel free to use the [Documnetaton for Gradient Boost Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html)

In [17]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(loss = 'deviance', learning_rate = 0.1, n_estimators =20,min_samples_split=3,max_depth = 3,max_features = 'sqrt',random_state=43)
classifier.fit(X_train, y_train)


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features='sqrt', max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=3,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=43, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

Now lets predict with our test set

In [0]:
y_pred = classifier.predict(X_test)

Now lets evaluate the accuracy , F1 score and the Confusion Matrix in order to check how well our model is classifying new data

---

First lets see how model works with our tarining examples

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY ---------------------->",acc_train)
print("F1 SCORE ---------------------->",f1_train)

Traing set results
ACCURACY ----------------------> 0.875
F1 SCORE ----------------------> 0.8709885455631511


Now lets see how well is our model. So now lets evaluate with our test set

In [20]:
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY ---------------------->",acc_test)
print("F1 SCORE ---------------------->",f1_test)

Test set results
ACCURACY ----------------------> 0.7598425196850394
F1 SCORE ----------------------> 0.7456802239154305


Not bad, 

Now lets visualize the Confusion Matrix

In [21]:
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[76  0  0  2]
 [ 3 30 11  3]
 [ 8 25 31  7]
 [ 0  1  1 56]]


Our Foresting algorithm with Bosting technique(here Gradient Boost) has done well in predicting our Train as well as Test set. So it has made the **appropriate fitting**

We have obtained this great accuracy for this challenging Dataset. If this dataset was fed in a normal Random Forest model, then it would have given a higher variance problem. But in Gradient Boosting, we were able to achieve this good accuracy and also not higher variance.
